---
- name: Install vsftpd and semanage
  dnf:
    name:
      - vsftpd
      - policycoreutils-python
    state: latest
#   update_cache: true
- name: Start vsftpd
  systemd:
    name: vsftpd
    enabled: 'yes'
    state: started
- name: Create pub folder and fix permissions
  file:
    path: /var/ftp/pub
    state: directory
    mode: '2755'
- name: Create upload folder and permissions
  file:
    path: /var/ftp/pub/upload
    state: directory
    mode: '2777'
- name: FTP config deploy
  template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd/vsftpd.conf
  notify:
    - restart vsftpd
- name: SElinux boolean anon write permissions 
  seboolean:
    name: ftpd_anon_write
    state: yes
    persistent: yes
- name: Configure SElinux context
  sefcontext:
    target: '/var/ftp/pub/upload'
    setype: public_content_rw_t
    state: present

- name: Apply SElinux context
  command: restorecon -irv /var/ftp/pub/upload

