- name: Install vsftpd
  dnf:
    name:
      - vsftpd
    state: latest
#   update_cache: true
- name: Start vsftpd
  systemd:
    name: vsftpd
    enabled: 'yes'
    state: started
- name: Check status of vsftpd
  service_facts: 
  register: service_state
- debug:
    var: 'service_state.ansible_facts.services["vsftpd.service"].state'
- name: Create pub folder and fix permissions
  file:
    path: /var/ftp/pub
    state: directory
    mode: '2755'
- name: Create upload folder and permissions
  file:
    path: /var/ftp/pub/upload
    state: directory
    mode: '2777'
- name: FTP config deploy
  template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd/vsftpd.conf
  notify:
    - restart vsftpd
- name: SElinux for Anonymous FTP upload
  seboolean:
    name: ftpd_anon_write
    state: true
    persistent: yes
- name: SElinux file context pub
  sefcontext:
    target: "/var/ftp/pub"
    setype: public_content_rw_t
    state: present
- name: SElinux file context pub
  sefcontext:
    target: "/var/ftp/pub/upload"
    setype: public_content_rw_t
    state: present
